controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# score_publication:
#   path: /score/{role}/publication
#   methods: ['GET']
#   defaults:
#     _controller: App\Controller\API\UserRatingsByRoleController::__invoke
#     # _api_resource_class: App\Entity\Book
#     _api_operation_name: get_publication
